const MovieList = [
    {
      id: 1,
      name: "Mission Impossible - Dead Reckoning Part One",
      image: "https://cdn.dnaindia.com/sites/default/files/2023/07/10/2598537-mi-7.jpg?im=FitAndFill=(1200,900)",
      category: "Action/Thriller",
      time: "2h 31m",
      language: "English",
      hall: "QFX cinema Butwal",
    },
    {
      id: 2,
      name: "The Equalizer 3",
      image: "https://www.filmonger.com/wp-content/uploads/2023/08/TheEqualizer3-director-teaser.webp",
      category: "Action/Thriller",
      time: "2h 31m",
      language: "English",
      hall: "QFX cinema Butwal",
    },
    { 
      id: 3,
      name: "Inception 2: Beyond Dreams",
      image: "https://assetsio.reedpopcdn.com/MarvelsHeader_rUbTNsM.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp",
      category: "Sci-Fi/Action",
      time: "2h 45m",
      language: "English",
      hall: "Cineplex City Center",
    },
    {
      id: 4,
      name: "The Matrix Resurrections",
      image: "https://www.gstatic.com/webp/gallery/2.jpg",
      category: "Sci-Fi/Action",
      time: "2h 20m",
      language: "English",
      hall: "AMC Theatres",
    },
    {
      id: 5,
      name: "Dune",
      image: "https://www.indiewire.com/wp-content/uploads/2021/09/DUNE-Imax-Poster.jpg",
      category: "Sci-Fi/Adventure",
      time: "2h 35m",
      language: "English",
      hall: "Regal Cinemas",
    },
    {
      id: 6,
      name: "The Batman",
      image: "https://cdn.mos.cms.futurecdn.net/5zs7aDkySPDd3FqJtJTDmM-1200-80.jpg",
      category: "Action/Crime",
      time: "2h 55m",
      language: "English",
      hall: "Cineworld",
    },
    {
      id: 7,
      name: "Avatar 2",
      image: "https://www.joblo.com/assets/images/joblo/posters/2022/06/avatar2-final.jpg",
      category: "Sci-Fi/Adventure",
      time: "3h 10m",
      language: "English",
      hall: "Vue Cinemas",
    },
    {
      id: 8,
      name: "Jurassic World: Dominion",
      image: "https://cdn.collider.com/wp-content/uploads/2021/06/Jurassic-World-Dominion-poster.jpg",
      category: "Action/Adventure",
      time: "2h 45m",
      language: "English",
      hall: "Odeon Cinemas",
    },
    {
      id: 9,
      name: "Spider-Man: No Way Home",
      image: "https://cdn.collider.com/wp-content/uploads/2021/08/spider-man-no-way-home-poster.jpg",
      category: "Action/Adventure",
      time: "2h 28m",
      language: "English",
      hall: "Empire Cinemas",
    },
    {
      id: 10,
      name: "Black Panther: Wakanda Forever",
      image: "https://cdn.collider.com/wp-content/uploads/2021/12/black-panther-wakanda-forever-poster.jpg",
      category: "Action/Adventure",
      time: "2h 40m",
      language: "English",
      hall: "AMC Theatres",
    }
  ];


export default MovieList;